#!/usr/bin/env python
# Copyright 2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

import portage.versions
import xmlrpc.client
from tatt.tattConfig import tattConfig as tattConfig

if __name__ == "__main__":
	tattconfig = tattConfig()

	url = 'https://bugs.gentoo.org/xmlrpc.cgi'
	bugzilla = xmlrpc.client.ServerProxy(url)

	bug_id = @@BUG@@

	params = {}
	params['Bugzilla_api_key'] = tattconfig['key']
	params['ids'] = [bug_id]
	bug_xml = bugzilla.Bug.get(params)['bugs'][0]
	has_my_arch = False
	has_other_arches = False
	for cc in bug_xml['cc']:
		body, domain = cc.split('@', 1)
		if domain == 'gentoo.org':
			if body == '@@ARCH@@':
				has_my_arch = True
			elif body in portage.archlist:
				has_other_arches=True

	# We don't close bugs which still have other arches for obvious reasons,
	# and security bugs because stabilization is not the last step for them.
	params['cc'] = {}
	params['cc']['remove'] = ['@@ARCH@@@gentoo.org']
	params['comment'] = {}
	if has_other_arches or 'Security' in bug_xml['product']:
		params['comment']['body'] = '@@ARCH@@ stable'
	else:
		params['comment']['body'] = '@@ARCH@@ stable, closing'
		params['status'] = 'RESOLVED'
		params['resolution'] = 'FIXED'
	bugzilla.Bug.update(params)
